/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AuthenticatedImport } from "./routes/_authenticated";
import { Route as AuthenticatedIndexImport } from "./routes/_authenticated/index";
import { Route as AuthLoginImport } from "./routes/auth/login";
import { Route as AuthenticatedDashboardWalletIndexImport } from "./routes/_authenticated/dashboard/wallet/index";
import { Route as AuthenticatedDashboardVerifyIndexImport } from "./routes/_authenticated/dashboard/verify/index";
import { Route as AuthenticatedDashboardHomeIndexImport } from "./routes/_authenticated/dashboard/home/index";
import { Route as AuthenticatedDashboardWalletCashInCashOutImport } from "./routes/_authenticated/dashboard/wallet/cash-in-cash-out";
import { Route as AuthenticatedDashboardWalletCashHistoryImport } from "./routes/_authenticated/dashboard/wallet/cash-history";
import { Route as AuthenticatedDashboardHomeUsersImport } from "./routes/_authenticated/dashboard/home/users";
import { Route as AuthenticatedDashboardHomeEventsImport } from "./routes/_authenticated/dashboard/home/events";

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthLoginRoute = AuthLoginImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedDashboardWalletIndexRoute =
  AuthenticatedDashboardWalletIndexImport.update({
    id: "/dashboard/wallet/",
    path: "/dashboard/wallet/",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedDashboardVerifyIndexRoute =
  AuthenticatedDashboardVerifyIndexImport.update({
    id: "/dashboard/verify/",
    path: "/dashboard/verify/",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedDashboardHomeIndexRoute =
  AuthenticatedDashboardHomeIndexImport.update({
    id: "/dashboard/home/",
    path: "/dashboard/home/",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedDashboardWalletCashInCashOutRoute =
  AuthenticatedDashboardWalletCashInCashOutImport.update({
    id: "/dashboard/wallet/cash-in-cash-out",
    path: "/dashboard/wallet/cash-in-cash-out",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedDashboardWalletCashHistoryRoute =
  AuthenticatedDashboardWalletCashHistoryImport.update({
    id: "/dashboard/wallet/cash-history",
    path: "/dashboard/wallet/cash-history",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedDashboardHomeUsersRoute =
  AuthenticatedDashboardHomeUsersImport.update({
    id: "/dashboard/home/users",
    path: "/dashboard/home/users",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedDashboardHomeEventsRoute =
  AuthenticatedDashboardHomeEventsImport.update({
    id: "/dashboard/home/events",
    path: "/dashboard/home/events",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated/": {
      id: "/_authenticated/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/dashboard/home/events": {
      id: "/_authenticated/dashboard/home/events";
      path: "/dashboard/home/events";
      fullPath: "/dashboard/home/events";
      preLoaderRoute: typeof AuthenticatedDashboardHomeEventsImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/dashboard/home/users": {
      id: "/_authenticated/dashboard/home/users";
      path: "/dashboard/home/users";
      fullPath: "/dashboard/home/users";
      preLoaderRoute: typeof AuthenticatedDashboardHomeUsersImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/dashboard/wallet/cash-history": {
      id: "/_authenticated/dashboard/wallet/cash-history";
      path: "/dashboard/wallet/cash-history";
      fullPath: "/dashboard/wallet/cash-history";
      preLoaderRoute: typeof AuthenticatedDashboardWalletCashHistoryImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/dashboard/wallet/cash-in-cash-out": {
      id: "/_authenticated/dashboard/wallet/cash-in-cash-out";
      path: "/dashboard/wallet/cash-in-cash-out";
      fullPath: "/dashboard/wallet/cash-in-cash-out";
      preLoaderRoute: typeof AuthenticatedDashboardWalletCashInCashOutImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/dashboard/home/": {
      id: "/_authenticated/dashboard/home/";
      path: "/dashboard/home";
      fullPath: "/dashboard/home";
      preLoaderRoute: typeof AuthenticatedDashboardHomeIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/dashboard/verify/": {
      id: "/_authenticated/dashboard/verify/";
      path: "/dashboard/verify";
      fullPath: "/dashboard/verify";
      preLoaderRoute: typeof AuthenticatedDashboardVerifyIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/dashboard/wallet/": {
      id: "/_authenticated/dashboard/wallet/";
      path: "/dashboard/wallet";
      fullPath: "/dashboard/wallet";
      preLoaderRoute: typeof AuthenticatedDashboardWalletIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedDashboardHomeEventsRoute: typeof AuthenticatedDashboardHomeEventsRoute;
  AuthenticatedDashboardHomeUsersRoute: typeof AuthenticatedDashboardHomeUsersRoute;
  AuthenticatedDashboardWalletCashHistoryRoute: typeof AuthenticatedDashboardWalletCashHistoryRoute;
  AuthenticatedDashboardWalletCashInCashOutRoute: typeof AuthenticatedDashboardWalletCashInCashOutRoute;
  AuthenticatedDashboardHomeIndexRoute: typeof AuthenticatedDashboardHomeIndexRoute;
  AuthenticatedDashboardVerifyIndexRoute: typeof AuthenticatedDashboardVerifyIndexRoute;
  AuthenticatedDashboardWalletIndexRoute: typeof AuthenticatedDashboardWalletIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDashboardHomeEventsRoute: AuthenticatedDashboardHomeEventsRoute,
  AuthenticatedDashboardHomeUsersRoute: AuthenticatedDashboardHomeUsersRoute,
  AuthenticatedDashboardWalletCashHistoryRoute:
    AuthenticatedDashboardWalletCashHistoryRoute,
  AuthenticatedDashboardWalletCashInCashOutRoute:
    AuthenticatedDashboardWalletCashInCashOutRoute,
  AuthenticatedDashboardHomeIndexRoute: AuthenticatedDashboardHomeIndexRoute,
  AuthenticatedDashboardVerifyIndexRoute:
    AuthenticatedDashboardVerifyIndexRoute,
  AuthenticatedDashboardWalletIndexRoute:
    AuthenticatedDashboardWalletIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

export interface FileRoutesByFullPath {
  "": typeof AuthenticatedRouteWithChildren;
  "/auth/login": typeof AuthLoginRoute;
  "/": typeof AuthenticatedIndexRoute;
  "/dashboard/home/events": typeof AuthenticatedDashboardHomeEventsRoute;
  "/dashboard/home/users": typeof AuthenticatedDashboardHomeUsersRoute;
  "/dashboard/wallet/cash-history": typeof AuthenticatedDashboardWalletCashHistoryRoute;
  "/dashboard/wallet/cash-in-cash-out": typeof AuthenticatedDashboardWalletCashInCashOutRoute;
  "/dashboard/home": typeof AuthenticatedDashboardHomeIndexRoute;
  "/dashboard/verify": typeof AuthenticatedDashboardVerifyIndexRoute;
  "/dashboard/wallet": typeof AuthenticatedDashboardWalletIndexRoute;
}

export interface FileRoutesByTo {
  "/auth/login": typeof AuthLoginRoute;
  "/": typeof AuthenticatedIndexRoute;
  "/dashboard/home/events": typeof AuthenticatedDashboardHomeEventsRoute;
  "/dashboard/home/users": typeof AuthenticatedDashboardHomeUsersRoute;
  "/dashboard/wallet/cash-history": typeof AuthenticatedDashboardWalletCashHistoryRoute;
  "/dashboard/wallet/cash-in-cash-out": typeof AuthenticatedDashboardWalletCashInCashOutRoute;
  "/dashboard/home": typeof AuthenticatedDashboardHomeIndexRoute;
  "/dashboard/verify": typeof AuthenticatedDashboardVerifyIndexRoute;
  "/dashboard/wallet": typeof AuthenticatedDashboardWalletIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/auth/login": typeof AuthLoginRoute;
  "/_authenticated/": typeof AuthenticatedIndexRoute;
  "/_authenticated/dashboard/home/events": typeof AuthenticatedDashboardHomeEventsRoute;
  "/_authenticated/dashboard/home/users": typeof AuthenticatedDashboardHomeUsersRoute;
  "/_authenticated/dashboard/wallet/cash-history": typeof AuthenticatedDashboardWalletCashHistoryRoute;
  "/_authenticated/dashboard/wallet/cash-in-cash-out": typeof AuthenticatedDashboardWalletCashInCashOutRoute;
  "/_authenticated/dashboard/home/": typeof AuthenticatedDashboardHomeIndexRoute;
  "/_authenticated/dashboard/verify/": typeof AuthenticatedDashboardVerifyIndexRoute;
  "/_authenticated/dashboard/wallet/": typeof AuthenticatedDashboardWalletIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ""
    | "/auth/login"
    | "/"
    | "/dashboard/home/events"
    | "/dashboard/home/users"
    | "/dashboard/wallet/cash-history"
    | "/dashboard/wallet/cash-in-cash-out"
    | "/dashboard/home"
    | "/dashboard/verify"
    | "/dashboard/wallet";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/auth/login"
    | "/"
    | "/dashboard/home/events"
    | "/dashboard/home/users"
    | "/dashboard/wallet/cash-history"
    | "/dashboard/wallet/cash-in-cash-out"
    | "/dashboard/home"
    | "/dashboard/verify"
    | "/dashboard/wallet";
  id:
    | "__root__"
    | "/_authenticated"
    | "/auth/login"
    | "/_authenticated/"
    | "/_authenticated/dashboard/home/events"
    | "/_authenticated/dashboard/home/users"
    | "/_authenticated/dashboard/wallet/cash-history"
    | "/_authenticated/dashboard/wallet/cash-in-cash-out"
    | "/_authenticated/dashboard/home/"
    | "/_authenticated/dashboard/verify/"
    | "/_authenticated/dashboard/wallet/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  AuthLoginRoute: typeof AuthLoginRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/auth/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/dashboard/home/events",
        "/_authenticated/dashboard/home/users",
        "/_authenticated/dashboard/wallet/cash-history",
        "/_authenticated/dashboard/wallet/cash-in-cash-out",
        "/_authenticated/dashboard/home/",
        "/_authenticated/dashboard/verify/",
        "/_authenticated/dashboard/wallet/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/home/events": {
      "filePath": "_authenticated/dashboard/home/events.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/home/users": {
      "filePath": "_authenticated/dashboard/home/users.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/wallet/cash-history": {
      "filePath": "_authenticated/dashboard/wallet/cash-history.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/wallet/cash-in-cash-out": {
      "filePath": "_authenticated/dashboard/wallet/cash-in-cash-out.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/home/": {
      "filePath": "_authenticated/dashboard/home/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/verify/": {
      "filePath": "_authenticated/dashboard/verify/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/wallet/": {
      "filePath": "_authenticated/dashboard/wallet/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
