import Footer from "../components/homepage/footer/Footer";
import Navbar from "../components/Navbar";
import "./globals.css";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
    icons: {
        icon: "/breeze/logo-fav.svg",
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Navbar />

                {children}
                <Footer />
            </body>
        </html>
    );
}
